version: "3"

services:
  mosquitto:
    image: eclipse-mosquitto:2
    hostname: mosquitto
    container_name: mosquitto
    restart: always

    networks:
      net_ms_api:
        ipv4_address: 172.8.1.11
    ports:
      - "1883:1883"
      - "9001:9001"

    user: root

    volumes:
      - ./mosquitto:/etc/mosquitto
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./passwd.sh:/passwd.sh

networks:
  net_ms_api:
    external: true
